import { SKY, BUILDING, WINDOW, DOOR, CLOUD, IN_FLOOR, IN_WALL, PC_DESK } from "./tiles";

/* ===== Outside Map (Jadielle City, Sylphe HQ) ===== */
export const OUTSIDE_MAP: number[][] = [];

// 0-3: Sky
OUTSIDE_MAP.push([7, 7, 7, 8, 8, 7, 7, 7, 7, 8, 7, 7, 7, 7, 8, 8, 7, 7, 7, 7]);
OUTSIDE_MAP.push([7, 7, 8, 8, 8, 8, 7, 7, 8, 8, 8, 7, 7, 8, 8, 8, 8, 7, 7, 7]);
OUTSIDE_MAP.push([7, 8, 8, 7, 7, 8, 7, 8, 8, 7, 8, 8, 8, 8, 7, 7, 8, 8, 7, 7]);
OUTSIDE_MAP.push([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]);

// 4-22: Building facade
for (let i = 0; i < 19; i++) {
  if (i % 3 === 0) {
    OUTSIDE_MAP.push([SKY, SKY, SKY, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, SKY, SKY, SKY]);
  } else {
    OUTSIDE_MAP.push([SKY, SKY, SKY, BUILDING, WINDOW, WINDOW, WINDOW, BUILDING, WINDOW, WINDOW, WINDOW, BUILDING, WINDOW, WINDOW, WINDOW, BUILDING, BUILDING, SKY, SKY, SKY]);
  }
}

// Bottom of building
OUTSIDE_MAP.push([SKY, SKY, SKY, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, SKY, SKY, SKY]);
OUTSIDE_MAP.push([SKY, SKY, SKY, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, SKY, SKY, SKY]);
OUTSIDE_MAP.push([2, 2, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, DOOR, DOOR, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, BUILDING, 2, 2, 2, 2]);

// Ground area
OUTSIDE_MAP.push([2, 0, 0, 0, 3, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 3, 0, 2, 2, 2]);
OUTSIDE_MAP.push([0, 0, 3, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0]);
OUTSIDE_MAP.push([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]);
OUTSIDE_MAP.push([0, 3, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 3, 0, 0, 0]);
OUTSIDE_MAP.push([4, 4, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4]);
OUTSIDE_MAP.push([4, 4, 4, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4]);

/* ===== Inside Map (Sylphe Corp interior) ===== */
export const INSIDE_MAP: number[][] = [
  [IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL],
  [IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL],
  [IN_WALL, IN_WALL, IN_WALL, IN_WALL, PC_DESK, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_WALL, IN_WALL, IN_WALL, IN_WALL],
  [IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_WALL, IN_WALL, IN_WALL, IN_WALL],
  [IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_WALL, IN_WALL, IN_WALL, IN_WALL],
  [IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_WALL, IN_WALL, IN_WALL, IN_WALL],
  [IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_WALL, IN_WALL, IN_WALL, IN_WALL],
  [IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_WALL, IN_WALL, IN_WALL, IN_WALL],
  [IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_FLOOR, IN_WALL, IN_WALL, IN_WALL, IN_WALL],
  [IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_FLOOR, IN_FLOOR, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL],
  [IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, DOOR, DOOR, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL],
  [IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL, IN_WALL],
];
